### ISSUE TITLE
Data polluted with foreign documents

### ISSUE THREAD

**Issue by cnrdh** [npolar/formula#24]
See the **parameter** edit http://api.npolar.no/editlog/6a644c2a-29ec-4af5-a81d-6e57d542e98a
where "data" and "resolution" stems from a previously edited timeseries

ch@arken:~/npolar/npdc-common$ npm list formula
npdc-common@2.1.1 /home/ch/npolar/npdc-common
└── formula@2.0.0  (git://github.com/npolar/formula.git#be5bd74c0954b4b1e6c39bd4d857109fae6b4491)

**Comment by rexso** [comment]
The problem seems to be that field values are persistent in the respective input fields even when a new model is set, because the form is not rebuilt when a new model is set (externally). This problem did not exist previous to commit b8a7ee3a9d8bcc1766d0dccd86d2b5b3e51cc9f3 because the form was rebuilt when model was manually set.

The build method was probably removed in an effort to improve performance. I believe that rebuilding the form is the best/only solution to the problem, and that performance will not be an issue as long as rebuilding only takes place when model is manually set (i.e. not by formula itself).

My proposal to get rid of this issue is to reimplement the build method, and call it when necessary to clear old data. When setting the model manually, we do not want to keep old data, thus making a complete rebuild necessary. Currently, as seen in [src/factories/form.js#L135-L143](https://github.com/npolar/formula/blob/be5bd74c0954b4b1e6c39bd4d857109fae6b4491/src/factories/form.js#L135-L143), fields with a new value defined in the new model will be updated properly, but fields with no specified value in the new model will just keep its current value (set or unset). What we need to do, is rebuild the form, then update the values based on the new model.

Note: The new model is updated correctly at first, but a complete form validation, either manually or during save, will add existing values to the model as long as the fields validates according to the schema.

## 

**This issue has been fixed as of ba26bd78562cad3589ff43141b161756a11abe89**.
~~Also, there's another problem. In your application you are using two separate instances of formula sharing the same model. The reason for this is that all instances of formula share the same model due to the formulaModel service. Of course, this also has to be fixed :)~~

**Comment by rexso** [comment]
Fixed in 87e9aa9105cae604ed95b3471bc018c911350753.
This marks [v2.1.0](https://github.com/npolar/formula/releases/tag/v2.1.0) :wine_glass:
